stages:
  - magento2-php
  - magento2-elasticsearch

build-magento2-php:
  image: docker.pp.ua/docker:latest
  stage: magento2-php
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t magento2-php:7.4 ./builds/php-fpm
    - docker tag magento2-php:7.4 $REGISTRY/magento2-php:7.4
    - docker push $REGISTRY/magento2-php:7.4

build-magento2-elasticsearch:
  image: docker.pp.ua/docker:latest
  stage: magento2-elasticsearch
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t magento2-elasticsearch:latest ./builds/elasticsearch
    - docker tag magento2-elasticsearch:latest $REGISTRY/magento2-elasticsearch:latest
    - docker push $REGISTRY/magento2-elasticsearch:latest