cluster.name: magento2
network.host: 0.0.0.0

cluster.blocks.read_only_allow_delete: false
cluster.routing.allocation.disk.threshold_enabled: false
discovery.type: single-node
xpack.security.enabled: false